#!/bin/bash
# Arrays
# Bash arrays can only have one dimension and indexes start at 0
# Messing with arrays


# Create an array
fav_nums=(3.14 2.718 .57721 4.6692)
echo "Pi : ${fav_nums[0]}"
	
# Add value to array
fav_nums[4]=1.618
echo "GR : ${fav_nums[4]}"
	
# Add group of values to array
fav_nums+=(1 7)
	
# Output all array values
for i in ${fav_nums[*]}; do
		echo $i;
done

# Output indexes   @ is used to print out them
for i in ${!fav_nums[@]}; do
		echo $i;
done

# Get number of items in arra  DON'T FORGET THE # SIGN before the array
echo "Array Length : ${#fav_nums[@]}"

# Get length of array element
echo "Index 3 length : ${#fav_nums[3]}"

# Sort an array
sorted_nums=($(for i in "${fav_nums[@]}"; do
		echo $i;
done | sort))

# Print out the sorted array
for i in ${sorted_nums[*]}; do
		echo $i;
done

# Delete array elemen. Here we're deleting the 2nd indext
unset 'sorted_nums[1]'

# Delete Array Completly
unset sorted_nums
